# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e0c46d9f8cc4e882fbfa00b134aab0d1"
name = "1account"
handle = "1account"
application_url = "https://peninsula-tension-lean-action.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-84a9cb58.myshopify.com"
include_config_on_deploy = true

[access.admin]
direct_api_mode = "online"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "unauthenticated_read_product_tags,write_customers,write_orders"

[auth]
redirect_urls = [
  "https://peninsula-tension-lean-action.trycloudflare.com/auth/callback",
  "https://peninsula-tension-lean-action.trycloudflare.com/auth/shopify/callback",
  "https://peninsula-tension-lean-action.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
