# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e0c46d9f8cc4e882fbfa00b134aab0d1"
name = "1account"
handle = "1account"
application_url = "https://wave-swiss-statute-webmaster.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-84a9cb58.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://wave-swiss-statute-webmaster.trycloudflare.com/auth/callback",
  "https://wave-swiss-statute-webmaster.trycloudflare.com/auth/shopify/callback",
  "https://wave-swiss-statute-webmaster.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
