# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "83f6a8d8e4bfc4004b05ce0b271f35ac"
name = "1account"
handle = "1account"
application_url = "https://fcc-lexington-artificial-layers.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-84a9cb58.myshopify.com"
include_config_on_deploy = true

[access.admin]
direct_api_mode = "online"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://fcc-lexington-artificial-layers.trycloudflare.com/auth/callback",
  "https://fcc-lexington-artificial-layers.trycloudflare.com/auth/shopify/callback",
  "https://fcc-lexington-artificial-layers.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
